#+TITLE: Devereaux's Story
#+SETUPFILE: ~/setup.org
#+LaTeX_CLASS: org-plain-latex
#+LaTeX_CLASS_OPTIONS: [article]
* The Malinois puppy
This is a book about Devereaux.  He was born on July 31, 2010.  He was one of 8
puppies in the 4th or D litter of Malinois pups from a kennel named Temple of the Tree located in San Diego, CA.  He was blue boy, which referred to the color of the bandanna wrapped around his neck.  All of the pups had different colored bandannas so that one could be told  apart from the next. Devereaux was one of the
biggest pups.  Since he was in the D litter he had to have a name that began with "D".  Since he is a Belgian breed he got a dutch name Devereaux.
* Maligator
When Dev was a pup he chewed everything.  He had lots of toys including a nasty bovine pizzle.  He had these really sharp teeth that could easily pierce through clothing.  He put holes in everybody's shirts. Because he was teething so much and with these sharp teeth like a lot of other Malinois pups he earned his nickname at the time of Mali(knows)gator.
* His First Trip
The first trip I took with Devereaux was to Washington state to Tyson ,
Wallula.  We stayed in a Red Roof Inn hotel.  During the day I kept Dev in the back of
my SUV.  Then after work was over we went to a nearby park.  He ran and ran in
this park and did not listen very well.  It was a long drive from home.  It was
for three weeks.  The hours sucked... I think I had to be there by 0500, so I had
to get up at like 0345 hrs which I hated.  The park was on a river...Dev loved walking by the river and running through the park.
* Lacrosse Balls
Through trials I figured out that the best toy for Dev was very hard rubber balls.  Of course there were Kongs
but those were $15 apiece.  What I came to realize was that lacrosse balls worked almost as well.  We now go to the park every night with at least a few of them.  I think I have ordered over 20 lacrosse balls for Dev.
* Training
Devereaux took little time to learn his commands (in the garage early before work)
and he picked up potty training really easily.  What was difficult was when I
got detailed to Oregon and because it was so far away I went without Dev and left him home with the rest
of the family.  Wow was I stressed as was the rest of the family back home.  Dev has come with me on every PHV detail/training I have gone on since then.
* Fascination with the Park
One of the favorite things that Dev likes to do is to go to the park nightly.  His internal clock goes off around 2330 hrs each night when he knows he is going to get to go.  I take him every night...rain or shine.  Normally he does like 4 sets of runs where I throw the ball he runs to get it , then I throw the next object which he runs to get and then over again.  By 10-12 runs he is usually a pretty tired pup and we are done.
* Chewing on Blankets
i do not understand why but this dog has a fascination with blankets.  This is most notable after eating.  He will jump up on the bed and just grab and hold a blanket in his mouth for no reason at all.  He will hold onto it for many minutes on end.  Its almost as if he enjoys doing this and that he gets satisfaction from having the material in his mouth.
* Favorite Games
We have tried many games but fetch is Dev's favorite.  Whether it is in the pool or at the park Dev loves to use his play drive to fetch things. he also likes to play with tug toys though we do not get to do that very much.
* Eating Habits
The healthier the better for Dev.  He loves vegetables and fruits, especially watermelon.  I think he is lactose intolerant as he get gastric distress's and diarrhea after consuming dairy products.  I feed him Origin original which is a high quality high protein no grain food.  He does get grains from me however.
* Dev's Worst Day
The worst experience we had with Dev was a result of being so intense when he plays.  The kids had div with a neighbor and there was a ball involved.  Well the ball was near the kids thigh and Dev went after it so forcefully with his teeth that he caused a laceration of the kids thigh. Luckily the kids parents were understanding.  I was at work. I get this terrible phone call that Dev had bitten the neighbors kid and that he would have to be in quarantine. Well bottom line is that we paid several hundred dollars for the medical bills and that was it.  I profoundly apologized to the neighbors and instructed the kids that they had to be careful with Dev especially around others and if there was a ball involved.
* Start as a Schutzhund Dog
Dev comes from working dog lines of Malinois.  Both of his parents were finished champion dogs.  We ignorantly thought we would be able to Schutzhund train Dev.  He has the drive and the genetics, unfortunately I did not have the knowledge.  So Dev knows the basics....sit, lie-down, speak, give paw, pizzle but that's about it.  I severely misjudged the time requirement for training.  It also was impossible training when he had 4 different masters all telling him different things.  In the end he learned the basic commands in German and English.  I also taught him Hebrew so that there would be a way that I could communicate with him that others did not know. In all training while a family was a very frustrating experience.
* Favorite Things in the World
If I had to answer what I believed were Dev's favorite things in the whole world I would say swimming and going to the park.  Mention either of these to Dev and he is on it, at attention, ears perked and ready to go.
* Travelling Buddy
Dev came with me on all of my PHV details when I was a veterinarian with FSIS USDA.  He was a eager and happy travel buddy.  I can't imagine being alone all of those weeks that I traveled .  Usually we go about two hours and then i let him out for a (potty) break.  It was on these trips that Dev saw snow (in Nevada) and travelled all of the states in the west.
* Butt Tumor
In 2018 I noted that Devereaux had a small perianal mass.  As it was most probably a perianal gland adenoma (aka hepatoid) tumor I arranged for Jon Fowler, DVM to neuter Dev and remove the tumore. The biopsy indeed showed it was perianal gland adenoma and that the excised margins were clear.
* Running the Fence
One of Dev's favorite things to do is to convince another dog to run along the fence with him when he is at the park.  He will run full speed at another dog with his tail wagging and try to get another dog on the other side of try fence to follow along with him.  Then they will run up and down along the length of the fence.  The amazing thing about this is that Dev does this carrying a ball in his mouth.
* I Am Worried
I am really worried long term for myself.  I love Devereaux so much.  If anything happens to him, I will be a total mess.  He better live a long time.  I am terrible at making decisions and I worry that someday (hopefully a long time from now) I will be forced into a Dev decision.  For now I am committed to loving him the best way I know how and I will love him the best way possible forever. I will take one day at a time and hope that it goes as slowly as possible. This is the anally way I know how to survive. I hope that we have as much time as is possible.
* Limiting Dev's Activity
I no longer feel comfortable letting Dev run in the park.  I worry that he will overdue it.  So we walk laps around the apartment complex.  Usually 2 laps per day.  That is both of our sum total exercise.
* Visits to Mommy
Dev is very happy to go on visits to mommy's house.  He no longer jumps into the back of the truck.  Rather he puts his front feet up and then I pick up his butt and put him in.  Works fine. He likes going outside there and reacting to the Rottweiler's next door.  Of course he is always looking for food if its available.
